2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_setup.py:_flush():70] Configure stats pid to 64808
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_setup.py:_flush():70] Loading settings from /Users/denisangel2k2/.config/wandb/settings
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_setup.py:_flush():70] Loading settings from /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/settings
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/run-20250519_202507-c7vl197g/logs/debug.log
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/run-20250519_202507-c7vl197g/logs/debug-internal.log
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x344e71850>
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:init():852] calling init triggers
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'epochs': 10, '_wandb': {}}
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:init():893] starting backend
2025-05-19 20:25:07,569 INFO    MainThread:64808 [wandb_init.py:init():897] sending inform_init request
2025-05-19 20:25:07,587 INFO    MainThread:64808 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-19 20:25:07,587 INFO    MainThread:64808 [wandb_init.py:init():907] backend started and connected
2025-05-19 20:25:07,593 INFO    MainThread:64808 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-05-19 20:25:07,594 INFO    MainThread:64808 [wandb_init.py:init():1005] updated telemetry
2025-05-19 20:25:07,597 INFO    MainThread:64808 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-19 20:25:08,173 INFO    MainThread:64808 [wandb_init.py:init():1104] starting run threads in backend
2025-05-19 20:25:08,247 INFO    MainThread:64808 [wandb_run.py:_console_start():2573] atexit reg
2025-05-19 20:25:08,247 INFO    MainThread:64808 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-19 20:25:08,247 INFO    MainThread:64808 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-19 20:25:08,247 INFO    MainThread:64808 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-19 20:25:08,249 INFO    MainThread:64808 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-19 20:25:59,652 WARNING MsgRouterThr:64808 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-19 20:25:59,656 INFO    MsgRouterThr:64808 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
